---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/Replace/hosts.yaml"
        group_file: "/home/ipvzero/Replace/groups.yaml"
        defaults_file: "/home/ipvzero/Replace/defaults.yaml"
